[package]
name = "cuadernillo"
version = "0.4.2"
description = "Editor markdown WYSIWYG con estructura de cuaderno tipo Zim"
authors = ["Antonio Rueda"]
edition = "2021"
license = "GPL-3.0-only"

[lib]
name = "cuadernillo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
futures-util = "0.3"
notify = "6"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-opener = "2"
